env:
    browser: true
    es2021: true
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:@typescript-eslint/recommended-requiring-type-checking"
    - "plugin:@typescript-eslint/strict"
    - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
    project: ["./tsconfig.json", ./test/tsconfig.json]
plugins:
    - "@typescript-eslint"
    - "prettier"
rules: { "prettier/prettier": ["error", "endOfLine": "auto"] }
